name: flutter_gastos01v1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  connectivity_plus: ^7.0.0
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.1
  sqflite: ^2.4.2
  supabase_flutter: ^2.10.3
  fl_chart: ^0.66.0
  pdf: ^3.11.3
  printing: ^5.14.2
  flutter_dotenv: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.4.0+1
  sqlite3_flutter_libs: ^0.5.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/gastosduquen03.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
